[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.9.4"

[dev]
  command = "npm run dev"
  port = 5000
  publish = "dist"
